home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.show_home, name='index'),
    path('redis/', views.show_redis, name='redis'),
    path('saveredis/', views.save_redis, name='saveredis'),
    path('wifi/', views.show_wifi, name='wifi'),
    path('savewifi/', views.save_wifi, name='savewifi'),
]

piswitch/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('home.urls')),
]

urlpatterns += staticfiles_urlpatterns()

home/forms.py
from django import forms


class RedisSettings(forms.Form):
    twitch_user = forms.CharField(max_length=255, label='Twitch Username')
    redis_pass = forms.CharField(max_length=255, label='Redis Password')
    redis_host = forms.CharField(max_length=255, label='Redis Hostname')
    redis_port = forms.IntegerField(label='Redis Port')
    redis_db = forms.IntegerField(label='Redis DB')

    def clean_redis_port(self):
        data = self.cleaned_data['redis_port']
        try:
            return int(data)
        except:
            raise forms.ValidationError('Please specify a valid port number.')

    def clean_redis_db(self):
        data = self.cleaned_data['redis_db']
        try:
            return int(data)
        except:
            raise forms.ValidationError('Please specify a valid db number.')


class WiFiSettings(forms.Form):
    wifi_sec_before_auto = forms.IntegerField()
    wifi_auto_config = forms.BooleanField(required=False)

    def clean_wifi_sec_before_auto(self):
        data = self.cleaned_data['wifi_sec_before_auto']
        try:
            return int(data)
        except:
            raise forms.ValidationError('Please specify a valid number of seconds.')

home/views.py
import logging
import os
from dotenv import load_dotenv
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from home.forms import RedisSettings, WiFiSettings
from pprint import pformat

logger = logging.getLogger('app')


def show_home(request):
    #  View: /
    return render(request, 'home.html')


def show_redis(request):
    #  View: /redis
    data = get_redis_settings(settings_file=settings.PISWITCH_SETTINGS)
    logger.debug(data)
    form = RedisSettings()
    form.fields['twitch_user'].initial = data['TWITCH_USER']
    form.fields['redis_pass'].initial = data['REDIS_PASS']
    form.fields['redis_host'].initial = data['REDIS_HOST']
    form.fields['redis_port'].initial = data['REDIS_PORT']
    form.fields['redis_db'].initial = data['REDIS_DB']
    return render(request, 'redis.html', {'data': data, 'form': form})


def save_redis(request):
    #  View: /saveredis
    logger.debug(pformat(request.POST))
    form = RedisSettings(request.POST)
    if not form.is_valid():
        logger.debug('INVALID FORM --------------')
        messages.add_message(request, messages.ERROR, form.errors, extra_tags='danger')
        return redirect('home:redis')
    else:
        logger.debug('VALID FORM ++++++++++++++++')
        data = {
            'TWITCH_USER': form.cleaned_data['twitch_user'],
            'REDIS_PASS': form.cleaned_data['redis_pass'],
            'REDIS_HOST': form.cleaned_data['redis_host'],
            'REDIS_PORT': form.cleaned_data['redis_port'],
            'REDIS_DB': form.cleaned_data['redis_db'],
        }
        logger.debug(data)
        write_settings(data, settings_file=settings.PISWITCH_SETTINGS)
        message = 'Redis settings successfully saved.'
        messages.add_message(request, messages.SUCCESS, message, extra_tags='success')
        return redirect('home:redis')


def show_wifi(request):
    #  View: /wifi
    form = WiFiSettings()
    form.fields['wifi_sec_before_auto'].initial = 300
    form.fields['wifi_auto_config'].initial = False
    return render(request, 'wifi.html', {'form': form})


def save_wifi(request):
    #  View: /savewifi
    logger.debug(pformat(request.POST))
    form = WiFiSettings(request.POST)
    if not form.is_valid():
        logger.debug('INVALID FORM --------------')
        messages.add_message(request, messages.ERROR, form.errors, extra_tags='danger')
        return redirect('home:wifi')
    else:
        logger.debug('VALID FORM ++++++++++++++++')
        data = {
            'wifi_sec_before_auto': form.cleaned_data['wifi_sec_before_auto'],
            'wifi_auto_config': form.cleaned_data['wifi_auto_config'],
        }
        logger.debug(data)
        write_settings(data, settings.WIFI_SETTINGS)
        message = 'WiFi settings successfully saved.'
        messages.add_message(request, messages.SUCCESS, message, extra_tags='success')
        return redirect('home:wifi')


def get_redis_settings(settings_file):
    load_dotenv(settings_file, override=True)
    return {
        'TWITCH_USER': os.environ.get('TWITCH_USER'),
        'REDIS_PASS': os.environ.get('REDIS_PASS'),
        'REDIS_HOST': os.environ.get('REDIS_HOST'),
        'REDIS_PORT': os.environ.get('REDIS_PORT'),
        'REDIS_DB': os.environ.get('REDIS_DB'),
    }


def write_settings(data, settings_file):
    output = ''
    for key, value in data.items():
        output += '{}={}\n'.format(key, value)
    with open(settings_file, 'w+') as f:
        f.write(output)

templates/home.html
{% extends "main.html" %}
{% block title %}Home{% endblock %}
{% block home_active %}active{% endblock %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">

            <h3>Settings Home</h3>

            <p class="lead">Panel Coming Soon...</p>

            <ul>
                <li><a href="{% url 'home:redis' %}">Redis Settings</a></li>
                <li><a href="{% url 'home:wifi' %}">WiFi Settings</a></li>
            </ul>

        </div>
    </div>
{% endblock %}

templates/main.html
{% load staticfiles %}
{% load home_tags %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<meta name="author" content="Shane Rice"/>
	<meta name="title" content="PiSwitch Manager"/>
	<meta name="description" content="Speedrun Results and Estimates"/>

	<title>PiSwitch Manager - {% block title %}{% endblock %}</title>

    <link rel="icon" href="{% static 'images/favicon.ico' %}">

	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'font-awesome/css/all.min.css' %}" rel="stylesheet">
	<link href="{% static 'main/css/main.css' %}" rel="stylesheet">

	{% block head %}{% endblock %}
</head>
<body>

<div class="container-fluid">

    {% block status %}
        <div class="row mt-1">
            <div class="col">
                {% if 'piswitch'|check_service_status %}
                    <div class="alert alert-success">PiSwitch Service is Active.</div>
                {% else %}
                    <div class="alert alert-danger">PiSwitch Service is Not Active!</div>
                {% endif %}
            </div>
        </div>
    {% endblock %}

    {% block menu %}
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-md navbar-light bg-light">
                    <a class="navbar-brand" href="{% url 'home:index' %}">PiSwitch</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar01"
                            aria-controls="navbar01" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbar01">

                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item {% block home_active %}{% endblock %}">
                                <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                            </li>
                            <li class="nav-item {% block redis_active %}{% endblock %}">
                                <a class="nav-link" href="{% url 'home:redis' %}">Redis</a>
                            </li>
                            <li class="nav-item {% block wifi_active %}{% endblock %}">
                                <a class="nav-link" href="{% url 'home:wifi' %}">WiFi</a>
                            </li>
                        </ul>

                    </div>
                </nav>
            </div>
        </div>
    {% endblock %}

    {% block heading %}
        <h1>PiSwitch Manager</h1>
    {% endblock %}

    {% block messages %}
        <div class="row">
            <div class="col">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.extra_tags }} alert-dismissible mt-1" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            {{ message.message|safe }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    {% endblock %}

    {% block body %}{% endblock %}

    {% block footer %}{% endblock %}

</div>

<script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'popper/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'font-awesome/js/all.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

{% block tail %}{% endblock %}

</body>
</html>

templates/redis.html
{% extends "main.html" %}
{% block title %}Redis Settings{% endblock %}
{% block redis_active %}active{% endblock %}
{% load crispy_forms_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row mt-1">
        <div class="col">

            <h3>Redis Settings</h3>

            <form action="{% url 'home:saveredis' %}" method="post">
                {{ form|crispy  }}
                <button type="submit" class="btn btn-success">Save Redis Settings</button>
            </form>

        </div>
    </div>
{% endblock %}

templates/wifi.html
{% extends "main.html" %}
{% block title %}WiFi Settings{% endblock %}
{% block wifi_active %}active{% endblock %}
{% load crispy_forms_tags %}

{% block head %}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">

            <h3>WiFi Settings</h3>

            <div class="alert alert-warning">Not Yet Functional</div>

            <form action="{% url 'home:savewifi' %}" method="post">
                {{ form|crispy  }}
                <button type="submit" class="btn btn-success">Save WiFi Settings</button>
            </form>

        </div>
    </div>
{% endblock %}